### ISSUE TITLE
[Help needed] Hana Studio JRE 16

### ISSUE THREAD

**Issue by NewFolk** [fmabap/AMDP_Pretty_Printer#22]
Hi and thank you for nice product.

Could you help me to enable it on Hana Studio?

Looks like it is JRE version issue. Could you help me to find the way to execute it with 16+ please?

![image](https://github.com/fmabap/AMDP_Pretty_Printer/assets/3263628/6f7e5d82-0536-4b82-971e-857e1f87677b)

![image](https://github.com/fmabap/AMDP_Pretty_Printer/assets/3263628/2b18f329-f230-4d07-b487-e2876743abce)

**Comment by fmabap** [comment]
Hi,
it looks like that your HANA Studio still uses Java JRE 11.

There should be a file hdbstudio.ini in the path of your HANA Studio  (looks like C:\SAP\hdbstudio) .

This file should contain an entry under -vm with the path to the used JRE. You must adjust it to the path of your new JRE bin folder. 
It should look like this example, but with your path. Please be aware, that you must use / instead of \ in the path.

<img width="640" alt="image" src="https://github.com/fmabap/AMDP_Pretty_Printer/assets/101019006/9224914b-7fd3-4131-a4d2-52d7d9754426">

A restart of the HANA Studio is required after this adjustment.

Kind regards
Frank

**Comment by NewFolk** [comment]
Perfect, thanks a lot. It works now!
